### PR TITLE
WEB 1602 fractal modal accessibility fix

### PR DESCRIPTION
**Pull request by patrickpatrickpatrick**
- cannot tab outside of modal, close is now a link rather than pseudoelement
- add back in button for closing modal
- linting js

### CODE REVIEW

**Comment by patrickpatrickpatrick** [comment]
tested on vam-web and it works

future modals will need to include the actual button in the html!

**Comment by patrickpatrickpatrick** [comment]
tested on vam-web and it works

future modals will need to include the actual button in the html!

**Comment by methodog** [comment]
looks good @patrickpatrickpatrick, just a couple of points though:
- is `jsModalClosed` custom event needed?
- the modal should only have `tabindex="0"` toggled on if/when it's shown, and conversely `aria-hidden="true"` too i guess

**Comment by patrickpatrickpatrick** [comment]
jsModalClosed is used for the image license overlay modal for the ETC image overlay, i think i probably should reimplement the way that modal works but that's probably out of the remit of this ticket?

**Pull request merged**
