### PR TITLE
add-icons-and-extend-fonts

### PR DESCRIPTION
**Pull request by Aleksandar-KirilovOSF**
Add person icons

### CODE REVIEW

**Comment by methodog** [comment]
Hi @Aleksandar-KirilovOSF - hope you're staying well.
I'm just trying to run your branch, but I suspect there may be some files missing. 

Did you forget to add the file containing your new `@mixin rem()` ?  (that is a handy mixin, by the way.)

Also, need to add `@import '../../components/blocks/top-header-bar/top-header-bar';` to `src/assets/styles/vam-style.scss`, I think.

Let me know if that's wrong / nonsense. Cheers, Luca

**Comment by Aleksandar-KirilovOSF** [comment]
Hey @methodog and thanks for the feedback, we will take a look and update this PR soon :)

**Comment by methodog** [comment]
Hi @Aleksandar-KirilovOSF - this is merged now, and in the latest version: `vam-fractal@0.4.6`
:)

**Comment by Aleksandar-KirilovOSF** [comment]
Thanks @methodog 🙇

**Pull request merged**
