### PR TITLE
add-icons

### PR DESCRIPTION
**Pull request by Aleksandar-KirilovOSF**
Add icons for shop site needs

### CODE REVIEW

**Comment by methodog** [comment]
Sorry for the long delay. Just a few of issues...

- The new *burger-nav* icon duplicates the *menu-hamburger* icon. There's an example of how you want to use it at the top-right of [vam.ac.uk](https://vam.ac.uk) at mobile size.

- The new *delivery* icon should be colored using `fill="currentColor"`, in the same way as you've corrected the *tick-circle* in this PR.

- New icons need to be added to the view for testing. Just add `'delivery'` to the end of the first list in `icons.config.js`

**Comment by Aleksandar-KirilovOSF** [comment]
Hello @methodog, thanks for the feedback. Comments are fixed :)

**Comment by methodog** [comment]
Thanks @Aleksandar-KirilovOSF, that's perfect!

**Comment by Aleksandar-KirilovOSF** [comment]
@methodog is that means I can update fractal library version now or I should wait for some kind of deploy?

**Comment by methodog** [comment]
@Aleksandar-KirilovOSF good question!
I've just released a new version: *0.3.165*
(e.g. `vam-fractal#v0.3.165`)

**Pull request merged**
