### PR TITLE
Mas 97 global footer implementation for multisite

### PR DESCRIPTION
**Pull request by nickbergquist**

### CODE REVIEW

**Review by methodog — COMMENTED** [review]
This is all great @nickbergquist !
The only little niggle i might have is that it doesn't use the `s-separated` class for those double backslashes. Ideally, any elements needing that styled separator would just have an `s-separated` class added in the HTML, rather than needing the duplicated `content: '\005C \005C';` styles in the CSS, even if those elements' styles may need to override some aspects of the default `s-separated` styles. And it may be the `s-separated` styles need tweaking too. That separator thing should look the same everywhere on the site (except for scale/colour/spacing which can be overriden), as it's part of the overall design. It's meant to be derived from the parallel lines of the V&A logo btw!

**Comment by nickbergquist** [comment]
Great stuff, thanks - I wasn't aware of the Services class so I'll implement it.

**Review by methodog — APPROVED** [review]
Excellent. PR approved! 
This is where our Jira/QA workflow process needs refining, especially concerning Fractal components. So that the ticket can be QA'd next, before merging the branch (into multisite), I've deployed it here for QA first https://vam-design-guide.surge.sh/components/preview/site-footer 
That way any tweaks that may be needed after QA feedback can be done in this branch, before merging.

**Comment by nickbergquist** [comment]
Modifications made for https://github.com/vanda/vam-web/issues/2065

**Pull request merged**
